[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  bblanchon/ArduinoJson@^7.2.0
  adafruit/Adafruit INA219@^1.2.3
  adafruit/Adafruit BusIO@^1.17.0
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^3.11.0
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
